import os
import urllib3
import pandas as pd
import requests
import snowflake.connector
import streamlit as st

# Disable insecure request warnings for self-signed certificates
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# Bypass proxy for internal Snowflake endpoint
os.environ["HTTP_PROXY"] = ""
os.environ["HTTPS_PROXY"] = ""
os.environ["NO_PROXY"] = "*"
os.environ["http_proxy"] = ""
os.environ["https_proxy"] = ""

# Page configuration
st.set_page_config(
    page_title="Incident Intelligence Q&A", page_icon="📝", layout="wide"
)

# Title
st.title("📝 Incident Intelligence - Ask Questions")
st.markdown("Powered by Snowflake Cortex Analyst")

# Sidebar with example questions
with st.sidebar:
    st.header("> Example Questions")
    examples = [
        "Which application accounts for the largest percentage of all 1 - Critical & 2 - High incidents in January 2026?",
        "What are the top 5 root causes for incidents?",
        "Show incident trend by month for the last 6 months",
        "Which applications have the most change-related incidents?",
        "How many 1 - Critical incidents were there last week?",
    ]
    for ex in examples:
        if st.button(ex, key=ex):
            st.session_state.question = ex

# Function to get Auth token pulling from st.secrets
@st.cache_data(ttl=3600)
def get_oauth_token():
    token_data = {
        "grant_type": "client_credentials",
        "client_id": st.secrets["azure_oauth"]["client_id"],
        "scope": st.secrets["azure_oauth"]["scope"],
        "client_secret": st.secrets["azure_oauth"]["secret"],
    }
    response = requests.post(
        st.secrets["azure_oauth"]["token_url"], data=token_data, verify=False
    )
    return response.json()["access_token"]

# Function to ask Cortex Analyst pulling URLs from st.secrets
def ask_cortex(question):
    oauth_token = get_oauth_token()
    
    # Call Cortex Analyst API using hidden URL
    headers = {
        "Authorization": f"Bearer {oauth_token}",
        "Content-Type": "application/json",
    }
    payload = {
        "messages": [
            {"role": "user", "content": [{"type": "text", "text": question}]}
        ],
        "semantic_model": f"{st.secrets['snowflake']['database']}.{st.secrets['snowflake']['schema']}.INCIDENT_V2",
    }

    # Bypass proxy for internal privatelink endpoint
    proxies = {"http": None, "https": None}
    response = requests.post(
        st.secrets["snowflake"]["cortex_url"], headers=headers, json=payload, verify=False, proxies=proxies
    )
    result = response.json()

    # Extract SQL statement
    sql_statement = None
    for content in result["message"]["content"]:
        if content["type"] == "sql":
            sql_statement = content["statement"]
            break

    if not sql_statement:
        raise Exception("No SQL statement generated by Cortex Analyst.")

    # Execute SQL in Snowflake using hidden connection settings
    conn = snowflake.connector.connect(
        host=st.secrets["snowflake"]["host"],
        account=st.secrets["snowflake"]["account"],
        authenticator="oauth",
        token=oauth_token,
        warehouse=st.secrets["snowflake"]["warehouse"],
        database=st.secrets["snowflake"]["database"],
        schema=st.secrets["snowflake"]["schema"],
        protocol="https",
        port=443,
    )
    
    try:
        df = pd.read_sql(sql_statement, conn)
    finally:
        conn.close()
        
    return df, sql_statement

# Main chat interface
question = st.text_input(
    "📝 Ask a question:",
    value=st.session_state.get("question", ""),
    placeholder="e.g., Which LOB has the most P1 incidents?",
)

if st.button("✨ Get Answer", type="primary"):
    if question:
        with st.spinner("🤖 Thinking..."):
            try:
                df, sql = ask_cortex(question)
                
                # Display results
                st.success("✅ Answer:")
                st.dataframe(df, use_container_width=True)
                
                # Show generated SQL in expander
                with st.expander("View Generated SQL"):
                    st.code(sql, language="sql")
                
                # Download button
                csv = df.to_csv(index=False)
                st.download_button(
                    "📥 Download as CSV",
                    csv,
                    "results.csv",
                    "text/csv",
                )
            except Exception as e:
                st.error(f"❌ Error: {str(e)}")
                st.write("Full error details:")
                st.exception(e)
    else:
        st.warning("⚠️ Please enter a question")

# Footer
st.markdown("---")
st.markdown(
    "**Tip**: Ask questions in plain English - Cortex Analyst will convert them to SQL automatically!"
)
